import pyautogui
from time import sleep
import ctypes
import sys


# no cmd digitar
#python
#from mouseinfo import mouseInfo
#mouseInfo()
#da enter

#AUTOMATIZA NOTAS DE ENTRADA NO SISTEMA EXACTUS COM BASE EM PLANILHA EXCEL XML
#PASSO A PASSO
#ABRIR A EXACTUS
pyautogui.click(792,745,duration=2)
sleep(1)
#CLICAR EM MOVIMENTOS
pyautogui.click(171,37,duration=2)
sleep(1)
#CLICAR EM REGISTRO DE ENTRADAS
pyautogui.click(213,62,duration=1)
#CLICAR EM DOCUMENTO
pyautogui.click(418,63,duration=1)
sleep(3)
#TECLAR PAGE DOWN
pyautogui.press('pagedown')


#COMECAR A FUNCAO ITERANDO SOBRE AS LINHAS DO EXCEL

#TECLAR F5
#TECLAR ENTER
#CLICAR EM CODIGO FISCAL
#FAZER O IF DE CFOP COM BASE NA PLANILHA EXCEL
#CLICAR EM COMPLEMENTO DO CODIGO FISCAL
#FAZER O IF DO COMPLEMENTO DO CODIGO FISCAL
#CLICAR EM ALIQUOTA, LIMPAR
#CLICAR EM BASE DE CALCULO, LIMPAR
#CLICAR EM IMPOSTO, LIMPAR
#CLICAR EM ISENTAS/NT, LIMPAR
#CLICAR EM VALOR AUXILAR, LIMPAR
#CLICAR EM BASE IMP. RETIDO, LIMPAR
#CLICAR EM IMPOSTO RETIDO, LIMPAR
#TECLAR ENTER
#ESPERAR 8SEC
#CLICAR ENTER
#ESPERAR 5SEC
#CLICAR EM QUANTIDADE DE PARCELAS
#CLICAR EM DIA PADRAO DO VENCIMENTO
#PREENCHER O PARCELAMENTO COM BASE NO IF
#CLICAR ENTER 
#SLEEP DE 3 SEC
#TECLAR PAGE DOWN
#FIM