import pyautogui
from time import sleep

# no cmd digitar
#python
#from mouseinfo import mouseInfo
#mouseInfo()
#da enter

#AUTOMATIZA NOTAS DE ENTRADA NO SISTEMA EXACTUS COM BASE EM PLANILHA EXCEL XML
#PASSO A PASSO
#JA ESTAR DENTRO DO SISTEMA
#CLICAR EM MOVIMENTOS
#CLICAR EM REGISTRO DE ENTRADAS
#CLICAR EM DOCUMENTO
#TECLAR PAGE DOWN

#COMECAR A FUNCAO ITERANDO SOBRE AS LINHAS DO EXCEL

#TECLAR F5
#TECLAR ENTER
#CLICAR EM CODIGO FISCAL
#FAZER O IF DE CFOP COM BASE NA PLANILHA EXCEL
#CLICAR EM COMPLEMENTO DO CODIGO FISCAL
#FAZER O IF DO COMPLEMENTO DO CODIGO FISCAL
#CLICAR EM ALIQUOTA, LIMPAR
#CLICAR EM BASE DE CALCULO, LIMPAR
#CLICAR EM IMPOSTO, LIMPAR
#CLICAR EM ISENTAS/NT, LIMPAR
#CLICAR EM VALOR AUXILAR, LIMPAR
#CLICAR EM BASE IMP. RETIDO, LIMPAR
#CLICAR EM IMPOSTO RETIDO, LIMPAR
#TECLAR ENTER
#ESPERAR 8SEC
#CLICAR ENTER
#ESPERAR 5SEC
#CLICAR EM QUANTIDADE DE PARCELAS
#CLICAR EM DIA PADRAO DO VENCIMENTO
#PREENCHER O PARCELAMENTO COM BASE NO IF
#CLICAR ENTER 
#SLEEP DE 3 SEC
#TECLAR PAGE DOWN
#FIM